name: Release

permissions:
  contents: write

on: [push]

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  create-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: release-dist-manifest
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            RUSTFLAGS: -C target-feature=+crt-static
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          # - target: arm64ec-pc-windows-msvc
          #   os: windows-latest
          # - target: aarch64-unknown-linux-musl
          #   os: ubuntu-24.04
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-24.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          # - target: aarch64-linux-android
          #   os: ubuntu-24.04
          - target: aarch64-linux-android
            os: ubuntu-22.04
          # - target: aarch64-linux-android
          #   os: macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: '-A warnings'
          toolchain: 'stable'
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build web
        run: |
          pnpm i
          pnpm run build
      - name: install cross
        if: startsWith(matrix.target, 'aarch64-linux-android')
        run: |
          # brew install podman
          # sudo apt update && sudo apt upgrade -y
          cargo install cross --git https://github.com/cross-rs/cross
          sudo apt-get -y install podman
      - name: build
        if: "!startsWith(matrix.target, 'aarch64-linux-android')"
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release -q --target=${{ matrix.target }}

          mkdir zip
          cp ./target/${{ matrix.target }}/release/yt-dlp-demo ./zip
          ls zip
          tar -czf ./yt-dlp-demo-${{ matrix.target }}.tar.gz -C zip .

      - name: upload
        if: "!startsWith(matrix.target, 'aarch64-linux-android')"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: yt-dlp-demo-${{ matrix.target }}.tar.gz

      - name: build android
        if: "startsWith(matrix.target, 'aarch64-linux-android')"
        run: |
          cross build --target=aarch64-linux-android --release
          mkdir zip
          cp ./target/aarch64-linux-android/release/yt-dlp-demo ./zip
          ls zip
          tar -czf ./yt-dlp-demo-${{ matrix.target }}.tar.gz -C zip .
      - name: upload
        if: "startsWith(matrix.target, 'aarch64-linux-android')"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: yt-dlp-demo-${{ matrix.target }}.tar.gz

