name: Release

permissions:
  contents: write

on: [push]

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  create-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: release-dist-manifest
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist-manifest/*.json,install.sh,install.ps1'

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            RUSTFLAGS: -C target-feature=+crt-static
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          # - target: arm64ec-pc-windows-msvc
          #   os: windows-latest
          # - target: aarch64-unknown-linux-musl
          #   os: ubuntu-24.04
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-24.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - target: aarch64-linux-android
            os: ubuntu-24.04
          # - target: aarch64-linux-android
          #   os: macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: '-A warnings'
          toolchain: 'stable'
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: build web
        run: |
          pnpm i
          pnpm run build
      - name: install cross
        if: startsWith(matrix.target, 'aarch64-linux-android')
        run: |
          ldd --version

          sudo apt update && sudo apt upgrade -y
          # sudo do-release-upgrade

          cargo install cross --git https://github.com/cross-rs/cross   --rev 7d75864e7812005156805587838f41eb3b30a270

          ldd --version

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          dry-run: ${{ !startsWith(github.ref, 'refs/tags/') }}
          bin: yt-dlp-demo
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ startsWith(github.ref, 'refs/tags/')  && github.ref || 'refs/tags/dummy' }}
        env:
          RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
      - name: Get target name for artifact
        id: artifact-target
        run: |
          target="${{ matrix.target }}"
          if [[ -z "${target}" ]]; then
            host=$(rustc -vV | grep -E '^host:' | cut -d' ' -f2)
            printf '%s\n' "artifact-target=${host}" >>"${GITHUB_OUTPUT}"
          elif [[ "${{ matrix.build-tool }}" == 'cargo-zigbuild' ]]; then
            printf '%s\n' "artifact-target=${target%%.*}" >>"${GITHUB_OUTPUT}"
          else
            printf '%s\n' "artifact-target=${target}" >>"${GITHUB_OUTPUT}"
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: yt-dlp-demo-${{ steps.artifact-target.outputs.artifact-target }}
          path: yt-dlp-demo-${{ steps.artifact-target.outputs.artifact-target }}.*
